# Generated by Django 3.2.7 on 2021-09-23 14:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_alter_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='likes',
            field=models.ManyToManyField(related_name='task_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
